spring.application.name=hue-travel-map

# Cấu hình Server
server.port=8080
server.servlet.context-path=/hue-travel-map

# Kết nối Database SQL Server
spring.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=HueTravelMapDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username= {your_database_username_here}
spring.datasource.password= {your_database_password_here}
spring.datasource.driverClassName= com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cấu hình SMTP Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= {your_email_here}
spring.mail.password= {your_email_password_here}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- CẤU HÌNH GOOGLE GEMINI AI ---
spring.ai.openai.api-key= {your_google_api_key_here}
spring.ai.openai.chat.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.completions-path=v1beta/openai/chat/completions
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.retry.max-attempts=1

# Cấu hình JWT
jwt.signerKey= {your_jwt_signer_key_here}

# Thư mục lưu trữ ảnh
app.upload.dir= {your_image_upload_directory_here}

# Tăng giới hạn dung lượng file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB